/**
 * Product catalog for Databricks Architecture Icons.
 *
 * Every `src` value refers to an official Databricks-published SVG stored in
 * `sources/`. Nothing in this library is redrawn or synthesised.
 *
 *   slug   file/id used across every generated artifact
 *   name   official product name as published by Databricks
 *   aka    former / alternative name, when the product has been renamed
 *   desc   one-line description suitable for a diagram caption or tooltip
 *   src    basename (no extension) of the official SVG in sources/
 *   kind   'icon'  -> Databricks Lava product icon (recolorable)
 *          'logo'  -> full-color project logo, used as published
 *   docs   canonical Databricks URL for the product
 */

export const PROJECT = {
  name: 'Databricks Architecture Icons',
  tagline: 'Icons for architecture diagrams, built from official Databricks artwork.',
  // The published site. Pages and links inside the site stay relative, so it
  // still works at any base path. This absolute form is only for the catalog,
  // the canonical link and the social card, which all need a full URL.
  url: 'https://oieduardorabelo.github.io/databricks-architecture-icons/',
  repository: 'https://github.com/oieduardorabelo/databricks-architecture-icons',
};

/**
 * Category colors are exact values from the published Databricks palette
 * (https://brandguides.brandfolder.com/databricks-extended-brand-guidelines).
 * The extended palette exists, in Databricks' own words, "to enhance the
 * comprehension of a message or to provide additional clarity through visual
 * hierarchy" — which is exactly what color-coding a diagram layer does.
 *
 * `contrast` is the ratio against the white glyph that sits on the tile.
 * WCAG 2.2 SC 1.4.11 requires 3:1 for non-text content; build.mjs enforces it.
 */
export const CATEGORIES = {
  platform: { label: 'Platform & Compute', color: '#FF3621', note: 'Lava 600 (primary)' },
  engineering: { label: 'Data Engineering', color: '#2272B4', note: 'Blue 600' },
  storage: { label: 'Storage & Databases', color: '#00875C', note: 'Green 700' },
  analytics: { label: 'Analytics & BI', color: '#1B5162', note: 'Navy 600' },
  ai: { label: 'AI & Agents', color: '#98102A', note: 'Maroon 600' },
  governance: { label: 'Governance & Security', color: '#1B3139', note: 'Navy 800 (primary)' },
  sharing: { label: 'Sharing & Collaboration', color: '#BA7B23', note: 'Yellow 700' },
  devtools: { label: 'Developer Tools & Apps', color: '#618794', note: 'Navy 500' },
};

/** Primary palette plus the extended grays, verbatim from the brand guidelines. */
export const BRAND = {
  lava: '#FF3621', // Lava 600 — primary accent, "bright and vibrant pops of color"
  navy800: '#1B3139', // Navy 800 — primary, large background
  navy900: '#0B2026', // extended — dark-mode background
  navy700: '#143D4A',
  navy600: '#1B5162',
  oatLight: '#F9F7F4', // primary, large background
  oatMedium: '#EEEDE9', // primary
  white: '#FFFFFF', // primary
  grayNav: '#303F47', // extended — Gray, Navigation
  grayText: '#5A6F77', // extended — Gray, Text
  grayLines: '#DCE0E2', // extended — Gray, Lines
};

export const PRODUCTS = [
  // ---------------------------------------------------------------- platform
  {
    slug: 'databricks',
    name: 'Databricks',
    // kind: 'logo' is load-bearing, not cosmetic. The brand guidelines list
    // "Don't recolor the logo" under What to avoid, so the build must never
    // run this mark through the mono or tile recoloring.
    desc: 'The Databricks logo mark. Use it to label the platform boundary in an architecture diagram.',
    category: 'platform',
    src: 'Databricks-Logo-Icon',
    kind: 'logo',
    docs: 'https://www.databricks.com/',
  },
  {
    slug: 'data-intelligence-platform',
    name: 'Data Intelligence Platform',
    desc: 'The unified platform for data engineering, analytics, AI and governance on one lakehouse foundation.',
    category: 'platform',
    src: 'icon-data-intelligence-platform',
    kind: 'icon',
    docs: 'https://www.databricks.com/product/data-intelligence-platform',
  },
  {
    slug: 'lakehouse',
    name: 'Lakehouse Architecture',
    desc: 'Open architecture combining data lake economics with warehouse reliability and ACID management.',
    category: 'platform',
    src: 'primary-icon-orange-delta-lakehouse',
    kind: 'icon',
    docs: 'https://www.databricks.com/product/data-lakehouse',
  },
  {
    slug: 'apache-spark',
    name: 'Apache Spark',
    desc: 'Managed, autoscaling Apache Spark for large-scale batch, streaming and ML processing.',
    category: 'platform',
    src: 'logo-apache-spark',
    kind: 'logo',
    docs: 'https://www.databricks.com/product/spark',
  },
  {
    slug: 'photon',
    name: 'Photon',
    desc: 'A native C++ vectorized query engine. It accelerates SQL and DataFrame work with no code changes.',
    category: 'platform',
    src: 'icon-orange-photon',
    kind: 'icon',
    docs: 'https://www.databricks.com/product/photon',
  },
  {
    slug: 'compute-clusters',
    name: 'Compute (Clusters)',
    desc: 'All-purpose and job compute resources that run notebooks, pipelines and jobs.',
    category: 'platform',
    src: 'clusterIcon',
    kind: 'icon',
    docs: 'https://docs.databricks.com/aws/en/compute/',
  },
  {
    slug: 'serverless-compute',
    name: 'Serverless Compute',
    desc: 'Fully managed, versionless compute that starts in seconds and autoscales without cluster administration.',
    category: 'platform',
    src: 'primary-icon-orange-scale',
    kind: 'icon',
    docs: 'https://www.databricks.com/product/serverless-compute',
  },
  {
    slug: 'databricks-runtime',
    name: 'Databricks Runtime',
    desc: 'An optimized runtime image with Spark, Delta and ML libraries. The ML variant adds GPU frameworks and AutoML.',
    category: 'platform',
    src: 'primary-icon-orange-runtime',
    kind: 'icon',
    docs: 'https://www.databricks.com/product/machine-learning-runtime',
  },
  {
    slug: 'spark-real-time-mode',
    name: 'Real-Time Mode for Apache Spark',
    desc: 'Structured Streaming execution mode delivering millisecond latency for time-critical pipelines.',
    category: 'platform',
    src: 'primary-icon-orange-speed',
    kind: 'icon',
    docs: 'https://www.databricks.com/product/data-engineering/spark-real-time-mode',
  },
  {
    slug: 'multicloud',
    name: 'Multicloud Deployment',
    desc: 'The same platform and governance model deployed across AWS, Azure and Google Cloud.',
    category: 'platform',
    src: 'primary-icon-orange-multicloud',
    kind: 'icon',
    docs: 'https://www.databricks.com/product/data-intelligence-platform',
  },

  // ------------------------------------------------------------- engineering
  {
    slug: 'lakeflow',
    name: 'Lakeflow',
    desc: 'The unified data engineering suite covering ingestion, declarative transformation and orchestration.',
    category: 'engineering',
    src: 'icon-lakeflow',
    kind: 'icon',
    docs: 'https://www.databricks.com/product/data-engineering',
  },
  {
    slug: 'lakeflow-connect',
    name: 'Lakeflow Connect',
    desc: 'Managed ingestion with 100+ connectors for SaaS applications, databases and cloud storage.',
    category: 'engineering',
    src: 'primary-icon-orange-connectors',
    kind: 'icon',
    docs: 'https://www.databricks.com/product/data-engineering/lakeflow-connect',
  },
  {
    slug: 'zerobus-ingest',
    name: 'Zerobus Ingest',
    desc: 'Broker-free streaming ingest over gRPC, REST and OpenTelemetry with roughly five-second freshness.',
    category: 'engineering',
    src: 'primary-icon-orange-input-ingest_',
    kind: 'icon',
    docs: 'https://www.databricks.com/product/data-engineering/lakeflow-connect/zerobus-ingest',
  },
  {
    slug: 'spark-declarative-pipelines',
    name: 'Apache Spark Declarative Pipelines',
    aka: 'Lakeflow Declarative Pipelines. Formerly Delta Live Tables (DLT)',
    desc: 'Declarative batch and streaming ETL with built-in data quality expectations, CDC and dependency management.',
    category: 'engineering',
    src: 'primary-icon-orange-lakeflow-pipelines',
    kind: 'icon',
    docs: 'https://www.databricks.com/product/data-engineering/spark-declarative-pipelines',
  },
  {
    slug: 'lakeflow-jobs',
    name: 'Lakeflow Jobs',
    aka: 'formerly Databricks Workflows',
    desc: 'Native orchestration for data, analytics and AI workflows, with control flow, retries and alerting.',
    category: 'engineering',
    src: 'primary-icon-orange-automation-orchestration',
    kind: 'icon',
    docs: 'https://www.databricks.com/product/data-engineering/lakeflow-jobs',
  },
  {
    slug: 'lakeflow-designer',
    name: 'Lakeflow Designer',
    desc: 'No-code, drag-and-drop pipeline authoring that generates governed, production-ready pipeline code.',
    category: 'engineering',
    src: 'dagicon',
    kind: 'icon',
    docs: 'https://www.databricks.com/product/data-engineering/lakeflow-designer',
  },
  {
    slug: 'auto-loader',
    name: 'Auto Loader',
    desc: 'Incrementally and idempotently ingests new files from cloud object storage as they arrive.',
    category: 'engineering',
    src: 'primary-icon-orange-access-connector',
    kind: 'icon',
    docs: 'https://docs.databricks.com/aws/en/ingestion/cloud-object-storage/auto-loader/',
  },
  {
    slug: 'structured-streaming',
    name: 'Structured Streaming',
    desc: 'The Apache Spark API for exactly-once stream processing in continuous, incremental pipelines.',
    category: 'engineering',
    src: 'streamIcon',
    kind: 'icon',
    docs: 'https://docs.databricks.com/aws/en/structured-streaming/',
  },
  {
    slug: 'lakebridge',
    name: 'Lakebridge',
    desc: 'Migration tooling that profiles legacy warehouses, converts code to ANSI SQL and validates the results.',
    category: 'engineering',
    src: 'icon-orange-reserved-keywords-parser',
    kind: 'icon',
    docs: 'https://www.databricks.com/solutions/migration',
  },

  // ----------------------------------------------------------------- storage
  {
    slug: 'delta-lake',
    name: 'Delta Lake',
    desc: 'Open table format adding ACID transactions, time travel and change data feed to object storage.',
    category: 'storage',
    src: 'icon-orange_delta-lake',
    kind: 'icon',
    docs: 'https://www.databricks.com/product/delta-lake-on-databricks',
  },
  {
    slug: 'apache-iceberg',
    name: 'Apache Iceberg',
    desc: 'First-class managed and foreign Iceberg tables, readable and writable through Unity and Iceberg REST catalogs.',
    category: 'storage',
    src: 'logo-color-apache-iceberg',
    kind: 'logo',
    docs: 'https://www.databricks.com/product/lakehouse-storage',
  },
  {
    slug: 'lakehouse-storage',
    name: 'Lakehouse Storage (Managed Tables)',
    desc: 'Self-optimizing managed Delta and Iceberg tables with automatic layout, compaction and caching.',
    category: 'storage',
    src: 'icon-orange-Delta-Table',
    kind: 'icon',
    docs: 'https://www.databricks.com/product/lakehouse-storage',
  },
  {
    slug: 'liquid-clustering',
    name: 'Liquid Clustering',
    desc: 'Partition-free, self-tuning data layout that adapts clustering keys to real query patterns.',
    category: 'storage',
    src: 'layerIcon',
    kind: 'icon',
    docs: 'https://docs.databricks.com/aws/en/delta/clustering',
  },
  {
    slug: 'predictive-optimization',
    name: 'Predictive Optimization',
    desc: 'AI-driven background maintenance that runs OPTIMIZE, VACUUM and statistics where they pay off most.',
    category: 'storage',
    src: 'gearOutlinedIcon',
    kind: 'icon',
    docs: 'https://docs.databricks.com/aws/en/optimizations/predictive-optimization',
  },
  {
    slug: 'lakebase',
    name: 'Lakebase',
    desc: 'Serverless Postgres OLTP database with branching, scale-to-zero and native lakehouse sync for apps and agents.',
    category: 'storage',
    src: 'icon-lakebase',
    kind: 'icon',
    docs: 'https://www.databricks.com/product/lakebase',
  },

  // --------------------------------------------------------------- analytics
  {
    slug: 'data-warehousing',
    name: 'Databricks Lakehouse (Data Warehousing)',
    desc: 'Serverless data warehouse built on open table formats and governed by Unity Catalog.',
    category: 'analytics',
    src: 'primary-icon-orange-data-warehouse',
    kind: 'icon',
    docs: 'https://www.databricks.com/product/databricks-lakehouse',
  },
  {
    slug: 'databricks-sql',
    name: 'Databricks SQL',
    desc: 'The SQL surface of the lakehouse: warehouses, editor, queries, alerts and BI connectivity.',
    category: 'analytics',
    src: 'icon-databricks-sql',
    kind: 'icon',
    docs: 'https://www.databricks.com/product/databricks-sql',
  },
  {
    slug: 'sql-warehouse',
    name: 'SQL Warehouse',
    desc: 'Serverless, Photon-powered SQL compute endpoint for BI tools, dashboards and ad hoc queries.',
    category: 'analytics',
    src: 'TableLightningIcon',
    kind: 'icon',
    docs: 'https://docs.databricks.com/aws/en/compute/sql-warehouse/',
  },
  {
    slug: 'lakehouse-rt',
    name: 'Lakehouse//RT',
    desc: 'Real-time warehouse tier serving millisecond queries at high concurrency directly on lake tables.',
    category: 'analytics',
    src: 'icon-lakehouse-rt',
    kind: 'icon',
    docs: 'https://www.databricks.com/product/lakehouse/real-time-lakehouse',
  },
  {
    slug: 'ai-bi',
    name: 'Databricks AI/BI',
    desc: 'The built-in business intelligence experience spanning dashboards, Genie spaces and semantics.',
    category: 'analytics',
    src: 'icon-ai-bi',
    kind: 'icon',
    docs: 'https://www.databricks.com/product/business-intelligence',
  },
  {
    slug: 'ai-bi-dashboards',
    name: 'AI/BI Dashboards',
    desc: 'Dashboards with natural-language chart authoring and forecasting. Publication needs no separate license.',
    category: 'analytics',
    src: 'dashboardIcon',
    kind: 'icon',
    docs: 'https://www.databricks.com/product/business-intelligence/ai-bi-dashboards',
  },
  {
    slug: 'lakehouse-federation',
    name: 'Lakehouse Federation',
    desc: 'Query and govern external systems such as Snowflake, BigQuery, Postgres and MySQL in place, without moving data.',
    category: 'analytics',
    src: 'icon-orange-Network-Data-Sources',
    kind: 'icon',
    docs: 'https://docs.databricks.com/aws/en/query-federation/',
  },

  // ---------------------------------------------------------------------- ai
  {
    slug: 'genie',
    name: 'Databricks Genie',
    desc: 'The agentic AI experience that answers questions and acts on governed enterprise data.',
    category: 'ai',
    src: 'icon-genie',
    kind: 'icon',
    docs: 'https://www.databricks.com/product/business-intelligence',
  },
  {
    slug: 'genie-one',
    name: 'Genie One',
    desc: 'AI coworker hub where business users ask questions, get grounded answers and trigger agentic actions.',
    category: 'ai',
    src: 'icon-genie-one-16x16',
    kind: 'icon',
    docs: 'https://www.databricks.com/product/genie/one',
  },
  {
    slug: 'genie-agents',
    name: 'Genie Agents',
    aka: 'formerly AI/BI Genie spaces',
    desc: 'Governed natural-language analytics spaces that answer business questions over curated data.',
    category: 'ai',
    src: 'speechBubbleIcon',
    kind: 'icon',
    docs: 'https://www.databricks.com/product/genie/agents',
  },
  {
    slug: 'genie-code',
    name: 'Genie Code',
    desc: 'Agentic coding partner for data teams that builds pipelines, dashboards, notebooks and ML workflows.',
    category: 'ai',
    src: 'GenieCodeIcon',
    kind: 'icon',
    docs: 'https://www.databricks.com/product/genie/code',
  },
  {
    slug: 'genie-deep-research',
    name: 'Genie Deep Research',
    desc: 'Multi-step research agent that investigates a question across governed data and returns a cited report.',
    category: 'ai',
    src: 'GenieDeepResearchIcon',
    kind: 'icon',
    docs: 'https://www.databricks.com/product/genie/one',
  },
  {
    slug: 'agent-bricks',
    name: 'Agent Bricks',
    desc: 'Platform for building, evaluating and governing enterprise AI agents grounded in your own data.',
    category: 'ai',
    src: 'icon-mosaic-ai-bricks',
    kind: 'icon',
    docs: 'https://www.databricks.com/product/artificial-intelligence/agent-bricks',
  },
  {
    slug: 'ai-search',
    name: 'Databricks AI Search',
    aka: 'formerly Databricks Vector Search / Mosaic AI Vector Search',
    desc: 'Managed hybrid vector and BM25 search with auto-syncing indexes and built-in reranking.',
    category: 'ai',
    src: 'SearchDataIcon',
    kind: 'icon',
    docs: 'https://www.databricks.com/product/artificial-intelligence/ai-search',
  },
  {
    slug: 'unity-ai-gateway',
    name: 'Unity AI Gateway',
    desc: 'Single control plane for model, MCP and agent access with guardrails, rate limits, budgets and audit.',
    category: 'ai',
    src: 'primary-icon-orange-authentication-service',
    kind: 'icon',
    docs: 'https://www.databricks.com/product/artificial-intelligence/unity-ai-gateway',
  },
  {
    slug: 'document-intelligence',
    name: 'Document Intelligence',
    desc: 'SQL-native parsing, extraction and classification that turns PDFs and images into governed structured data.',
    category: 'ai',
    src: 'icon-orange-Data-Parser-Normalizer-ETL-ELT',
    kind: 'icon',
    docs: 'https://www.databricks.com/product/artificial-intelligence/document-intelligence',
  },
  {
    slug: 'model-serving',
    name: 'Databricks Model Serving',
    aka: 'formerly Mosaic AI Model Serving',
    desc: 'Unified serverless endpoints for custom ML models, foundation models and agents, plus batch inference.',
    category: 'ai',
    src: 'CloudModelIcon',
    kind: 'icon',
    docs: 'https://www.databricks.com/product/model-serving',
  },
  {
    slug: 'model-training',
    name: 'Databricks Model Training',
    desc: 'Managed fine-tuning and custom model training on serverless H100 GPUs, without moving data.',
    category: 'ai',
    src: 'modelsIcon',
    kind: 'icon',
    docs: 'https://www.databricks.com/product/machine-learning/mosaic-ai-training',
  },
  {
    slug: 'mlflow',
    name: 'Managed MLflow',
    desc: 'Hosted MLflow for experiment tracking, GenAI tracing, evaluation and the Unity Catalog model registry.',
    category: 'ai',
    src: 'icon-orange-Full-Lifecycle-Machine-Learning',
    kind: 'icon',
    docs: 'https://www.databricks.com/product/managed-mlflow',
  },
  {
    slug: 'feature-store',
    name: 'Databricks Feature Store',
    desc: 'Governed feature registry with batch and low-latency online serving, and training/serving consistency.',
    category: 'ai',
    src: 'primary-icon-orange-cache-sync-reduction',
    kind: 'icon',
    docs: 'https://www.databricks.com/product/feature-store',
  },
  {
    slug: 'ai-functions',
    name: 'AI Functions',
    desc: 'SQL functions such as ai_query, ai_classify and ai_extract that call models directly inside queries.',
    category: 'ai',
    src: 'primary-icon-orange-built-in-functions',
    kind: 'icon',
    docs: 'https://docs.databricks.com/aws/en/large-language-models/ai-functions',
  },
  {
    slug: 'automl',
    name: 'Databricks AutoML',
    desc: 'Glass-box automated training that produces baseline models plus the editable notebooks that built them.',
    category: 'ai',
    src: 'primary-icon-orange-machine-learning',
    kind: 'icon',
    docs: 'https://www.databricks.com/product/automl',
  },
  {
    slug: 'customerlake',
    name: 'CustomerLake',
    desc: 'Agentic customer data platform with identity resolution, Customer 360 and marketing agents, native to the lakehouse.',
    category: 'ai',
    src: 'icon-customerlake',
    kind: 'icon',
    docs: 'https://www.databricks.com/product/customerlake-cdp',
  },

  // -------------------------------------------------------------- governance
  {
    slug: 'unity-catalog',
    name: 'Unity Catalog',
    desc: 'Unified governance for data, models, agents and MCP servers across clouds, under one permission model.',
    category: 'governance',
    src: 'icon-unity-catalog',
    kind: 'icon',
    docs: 'https://www.databricks.com/product/unity-catalog',
  },
  {
    slug: 'unity-catalog-semantics',
    name: 'Unity Catalog Semantics',
    desc: 'Central semantic layer of metric views and business definitions that grounds BI tools and AI agents.',
    category: 'governance',
    src: 'primary-icon-orange-context-enrichment',
    kind: 'icon',
    docs: 'https://www.databricks.com/product/unity-catalog/business-semantics',
  },
  {
    slug: 'data-lineage',
    name: 'Data & AI Lineage',
    desc: 'Automatic column-level lineage across tables, dashboards, models and agents for impact analysis and audit.',
    category: 'governance',
    src: 'primary-icon-orange-data-lineage',
    kind: 'icon',
    docs: 'https://docs.databricks.com/aws/en/data-governance/unity-catalog/data-lineage',
  },
  {
    slug: 'abac',
    name: 'Attribute-Based Access Control',
    desc: 'Tag- and attribute-driven policies that enforce row, column and object permissions at scale.',
    category: 'governance',
    src: 'lockOutlinedIcon',
    kind: 'icon',
    docs: 'https://docs.databricks.com/aws/en/data-governance/unity-catalog/abac/',
  },
  {
    slug: 'data-quality-monitoring',
    name: 'Data Quality Monitoring',
    aka: 'formerly Lakehouse Monitoring',
    desc: 'Automated profiling, freshness checks and anomaly detection over tables and inference logs.',
    category: 'governance',
    src: 'icon-orange-Observable-Metrics_0',
    kind: 'icon',
    docs: 'https://www.databricks.com/product/machine-learning/lakehouse-monitoring',
  },
  {
    slug: 'lakewatch',
    name: 'Lakewatch',
    desc: 'Open agentic SIEM for petabyte-scale security logs, detection-as-code and AI-assisted threat hunting.',
    category: 'governance',
    src: 'icon-orange-SIEM',
    kind: 'icon',
    docs: 'https://www.databricks.com/product/lakewatch',
  },
  {
    slug: 'system-tables',
    name: 'System Tables',
    desc: 'Built-in analytical tables exposing billing, usage, lineage, audit and job history for observability.',
    category: 'governance',
    src: 'visibleIcon',
    kind: 'icon',
    docs: 'https://docs.databricks.com/aws/en/admin/system-tables/',
  },
  {
    slug: 'enterprise-security',
    name: 'Enterprise Security',
    desc: 'Network isolation, customer-managed keys, private connectivity and compliance controls for the workspace.',
    category: 'governance',
    src: 'primary-icon-orange-enterprise-security',
    kind: 'icon',
    docs: 'https://www.databricks.com/trust/security-features',
  },

  // ----------------------------------------------------------------- sharing
  {
    slug: 'delta-sharing',
    name: 'Delta Sharing',
    desc: 'An open protocol for live, zero-copy data sharing across clouds, platforms and organizations.',
    category: 'sharing',
    src: 'shareIcon-orange',
    kind: 'icon',
    docs: 'https://www.databricks.com/product/delta-sharing',
  },
  {
    slug: 'opensharing',
    name: 'OpenSharing',
    desc: 'Linux Foundation standard extending governed sharing to data, models and agents across engines and clouds.',
    category: 'sharing',
    src: 'primary-icon-orange-open-source',
    kind: 'icon',
    docs: 'https://www.databricks.com/product/opensharing',
  },
  {
    slug: 'marketplace',
    name: 'Databricks Marketplace',
    desc: 'Open exchange for datasets, models, notebooks, dashboards and solution accelerators.',
    category: 'sharing',
    src: 'dataMarketplaceIcon',
    kind: 'icon',
    docs: 'https://www.databricks.com/product/marketplace',
  },
  {
    slug: 'clean-rooms',
    name: 'Databricks Clean Rooms',
    desc: 'Privacy-safe multi-party collaboration on shared data with no raw-data access, across clouds.',
    category: 'sharing',
    src: 'primary-icon-orange-collaborate',
    kind: 'icon',
    docs: 'https://www.databricks.com/product/collaboration/clean-rooms',
  },
  {
    slug: 'partner-connect',
    name: 'Partner Connect',
    desc: 'Guided setup that wires validated ingestion, BI and governance partner tools into your workspace.',
    category: 'sharing',
    src: 'primary-icon-orange-partner-connect',
    kind: 'icon',
    docs: 'https://www.databricks.com/partnerconnect',
  },

  // ---------------------------------------------------------------- devtools
  {
    slug: 'databricks-apps',
    name: 'Databricks Apps',
    desc: 'Serverless hosting for Python data and AI apps built with Streamlit, Dash or Gradio, with Unity Catalog auth.',
    category: 'devtools',
    src: 'appsIcon-orange',
    kind: 'icon',
    docs: 'https://www.databricks.com/product/databricks-apps',
  },
  {
    slug: 'notebooks',
    name: 'Databricks Notebooks',
    desc: 'Collaborative multi-language notebooks with built-in visualisation, versioning and AI assistance.',
    category: 'devtools',
    src: 'notebookIcon',
    kind: 'icon',
    docs: 'https://www.databricks.com/product/collaborative-notebooks',
  },
  {
    slug: 'workspace',
    name: 'Databricks Workspace',
    desc: 'A collaborative environment. It groups the notebooks, queries, dashboards, jobs and files of each team.',
    category: 'devtools',
    src: 'workspacesIcon-orange',
    kind: 'icon',
    docs: 'https://docs.databricks.com/aws/en/workspace/',
  },
  {
    slug: 'git-folders',
    name: 'Git Folders (Repos)',
    desc: 'Workspace folders backed by Git for branch-based development and CI/CD.',
    category: 'devtools',
    src: 'FolderBranchIcon',
    kind: 'icon',
    docs: 'https://www.databricks.com/product/repos',
  },
  {
    slug: 'asset-bundles',
    name: 'Databricks Asset Bundles',
    desc: 'Infrastructure-as-code packaging of jobs, pipelines and apps for repeatable multi-environment deploys.',
    category: 'devtools',
    src: 'briefcaseOutlinedIcon',
    kind: 'icon',
    docs: 'https://docs.databricks.com/aws/en/dev-tools/bundles/',
  },
  {
    slug: 'databricks-cli',
    name: 'Databricks CLI',
    desc: 'Command-line client for workspaces, jobs, compute, Unity Catalog and bundle deployment.',
    category: 'devtools',
    src: 'runIcon',
    kind: 'icon',
    docs: 'https://docs.databricks.com/aws/en/dev-tools/cli/',
  },
  {
    slug: 'databricks-connect',
    name: 'Databricks Connect',
    desc: 'Run local DataFrame code against remote Databricks compute from any IDE or application.',
    category: 'devtools',
    src: 'primary-icon-orange-unified',
    kind: 'icon',
    docs: 'https://docs.databricks.com/aws/en/dev-tools/databricks-connect/',
  },
  {
    slug: 'ide-integrations',
    name: 'IDE Integrations',
    desc: 'Official VS Code and PyCharm extensions for editing, syncing, running and debugging on Databricks.',
    category: 'devtools',
    src: 'codeIcon',
    kind: 'icon',
    docs: 'https://www.databricks.com/product/data-science/ide-integrations',
  },
  {
    slug: 'rest-api',
    name: 'REST API & SDKs',
    desc: 'Programmatic control of every platform resource, with official Python, Java, Go and JavaScript SDKs.',
    category: 'devtools',
    src: 'primary-icon-orange-webhook',
    kind: 'icon',
    docs: 'https://docs.databricks.com/api/workspace/introduction',
  },
  {
    slug: 'terraform-provider',
    name: 'Databricks Terraform Provider',
    desc: 'Official Terraform provider for declaring workspaces, compute, Unity Catalog objects and permissions.',
    category: 'devtools',
    src: 'primary-icon-orange-automation',
    kind: 'icon',
    docs: 'https://registry.terraform.io/providers/databricks/databricks/latest/docs',
  },
];

/** Extra full-color brand lockups shipped alongside the icon set. */
export const LOGOS = [
  { slug: 'databricks', name: 'Databricks', src: 'Databricks-Logo-Icon' },
  { slug: 'apache-spark', name: 'Apache Spark', src: 'logo-apache-spark' },
  { slug: 'delta-lake', name: 'Delta Lake', src: 'logo-color-delta-lake' },
  { slug: 'apache-iceberg', name: 'Apache Iceberg', src: 'logo-color-apache-iceberg' },
  { slug: 'mlflow', name: 'MLflow', src: 'logo-color-mlflow' },
  { slug: 'unity-catalog', name: 'Unity Catalog', src: 'logo-color-unity-catalog' },
  { slug: 'delta-sharing', name: 'Delta Sharing', src: 'delta-sharing-stacked-lockup-full-color-black-rgb' },
  { slug: 'terraform', name: 'Terraform', src: 'logo-color-terraform' },
];
